# Performance settings
backend = "glx";
vsync = true;
unredir-if-possible = true;

# Fade settings
fading = true;
fade-delta = 5;

# Opacity settings
opacity-rule = [
	"98:class_g = 'Alacritty' && focused",
	"95:class_g = 'Alacritty' && !focused"
];

# Shadow settings
shadow = true;
shadow-opacity = 0.25;
shadow-exclude = [
	"class_g != 'Rofi'"
];

# Rounded corners
corner-radius = 14;
rounded-corners-exclude = [
	"name = 'xmobar'"
];
